# Generated by Django 4.2.20 on 2025-04-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Url',
            field=models.URLField(default='https://example.com'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mac', 'MAC'), ('IPHONE', 'iPhone'), ('IPAD', 'iPad'), ('WATCH', 'Watch'), ('TV', 'TV'), ('ACCESSORIES', 'Accessories')], default='Mac', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
